### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by neobenedict** [naim94a/lumen#3] opened 2020-12-19 18:02 UTC
Any push/pull results in:
```
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ace/lumen/common/src/rpc/mod.rs:95:5
stack backtrace:
   0:     0x55e0a78469c0 - std::backtrace_rs::backtrace::libunwind::trace::h746c3e9529d524bc
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55e0a78469c0 - std::backtrace_rs::backtrace::trace_unsynchronized::h84373278bfb39e0c
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e0a78469c0 - std::sys_common::backtrace::_print_fmt::h517324efde750597
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e0a78469c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf594ab77fac89284
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55e0a7766c9c - core::fmt::write::h3868db8542c90941
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/fmt/mod.rs:1078:17
   5:     0x55e0a7845fc1 - std::io::Write::write_fmt::h3f6656f045fa877f
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/io/mod.rs:1519:15
   6:     0x55e0a7845a00 - std::sys_common::backtrace::_print::hda7655c057c24dcc
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55e0a7845a00 - std::sys_common::backtrace::print::h546a6c8431d46287
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55e0a7845a00 - std::panicking::default_hook::{{closure}}::h006dd083853faf51
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:208:50
   9:     0x55e0a78452b3 - std::panicking::default_hook::hf0f9afb1017317fc
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:225:9
  10:     0x55e0a78452b3 - std::panicking::rust_panic_with_hook::hb7a19826c029b1d6
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:591:17
  11:     0x55e0a7863e5d - std::panicking::begin_panic_handler::{{closure}}::hde71edcd925d0c5e
  12:     0x55e0a7863dcc - std::sys_common::backtrace::__rust_end_short_backtrace::h8a3c7d6cea578919
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55e0a7863d7d - rust_begin_unwind
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/panicking.rs:493:5
  14:     0x55e0a7764490 - core::panicking::panic_fmt::h20225113c4a2f8fd
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/panicking.rs:92:14
  15:     0x55e0a7764321 - core::panicking::panic_bounds_check::h5752306d250b5620
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/core/src/panicking.rs:69:5
  16:     0x55e0a7702f07 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb4f310b474cb9da1
  17:     0x55e0a77055aa - lumen::serve::{{closure}}::{{closure}}::h07416f8232903818
  18:     0x55e0a77ab71b - tokio::runtime::task::raw::poll::h1705a3383fc32a6c
  19:     0x55e0a7886cb7 - tokio::runtime::thread_pool::worker::Context::run_task::h59b2fa03a65ecc27
  20:     0x55e0a787e36e - tokio::runtime::task::raw::poll::ha196a4abbf2823db
  21:     0x55e0a787cfc3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4d117004d6fda901
  22:     0x55e0a7872297 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha186c7af46b2d32a
  23:     0x55e0a786bf35 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hea1090dbdcecbf5a
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:1328:9
  24:     0x55e0a786bf35 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d5723d3912bd325
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/alloc/src/boxed.rs:1328:9
  25:     0x55e0a786bf35 - std::sys::unix::thread::Thread::new::thread_start::hc17a425ca2995724
                               at /rustc/f74583445702e2e27ec4415376f2c540a83d7ded/library/std/src/sys/unix/thread.rs:71:17
  26:     0x7f5d29eb9fa3 - start_thread
  27:     0x7f5d29c604cf - clone
  28:                0x0 - <unknown>

```

Not using TLS. IDA 7.5. The hosted server you run works fine, just trying to run my own doesn't.

**Comment by naim94a** [comment] 2020-12-19 18:18
That's embarrassing, thanks for reporting the issue! it should be fixed now.

**Comment by neobenedict** [comment] 2020-12-19 18:21
It works now, but ssl has the error
`WARN  lumen > err: IOError(Custom { kind: UnexpectedEof, error: "early eof" })`

Non-ssl is fine.

**Comment by naim94a** [comment] 2020-12-19 18:43
I can't seem to reproduce the error. 

Could you please specify:
IDA: Version, OS, Architecture
Server: OS, Architecture

**Comment by naim94a** [comment] 2020-12-19 18:51
Note: A similar (although not exact) error may occur if the server is running without TLS and IDA is configured to use TLS.

**Comment by naim94a** [comment] 2020-12-19 20:24
I'm going to close this again since the original issue was solved.

> It works now, but ssl has the error
> `WARN lumen > err: IOError(Custom { kind: UnexpectedEof, error: "early eof" })`
> 
> Non-ssl is fine.

Feel free to open another issue (with details about env) if this isn't.

**Closed by naim94a** 2020-12-19 20:24 UTC
Labels: bug
